name: rec_dec
channels:
  - conda-forge
dependencies:
  - python=3.11
  - opencv
  - numpy
  - scikit-learn
  - scipy
  - collection
  - pip
  - pip:
      - mediapipe
      - facenet-pytorch
      - torch
      - torchvision
